name: softinsa_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# CONFIGURAÇÃO DO ÍCONE (Aquele que já funcionou)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_softinsa.png"
  min_sdk_android: 21

# CONFIGURAÇÃO DO SPLASH (Ecrã de abertura)
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_softinsa.png
  android_12:
    image: assets/logo_softinsa.png
    color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo_softinsa.png
    - assets/