// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkL134vEf_b3fIdY0xxRGCJrrTDAiJd9k',
    appId: '1:522600619451:web:3fe7b341bc39821030f89e',
    messagingSenderId: '522600619451',
    projectId: 'pint-b0c13',
    authDomain: 'pint-b0c13.firebaseapp.com',
    storageBucket: 'pint-b0c13.firebasestorage.app',
    measurementId: 'G-SJEXJX6JSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0Fc9RR2pYVKQCPYsEC5gb2-49-7tDo8',
    appId: '1:522600619451:android:f6d5cf0eec3ee9a530f89e',
    messagingSenderId: '522600619451',
    projectId: 'pint-b0c13',
    storageBucket: 'pint-b0c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68E1woqNuC3IoKGqRr-FIQXyYTLuh9Ds',
    appId: '1:522600619451:ios:e0246a64a0307e7030f89e',
    messagingSenderId: '522600619451',
    projectId: 'pint-b0c13',
    storageBucket: 'pint-b0c13.firebasestorage.app',
    iosBundleId: 'com.example.softinsaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68E1woqNuC3IoKGqRr-FIQXyYTLuh9Ds',
    appId: '1:522600619451:ios:e0246a64a0307e7030f89e',
    messagingSenderId: '522600619451',
    projectId: 'pint-b0c13',
    storageBucket: 'pint-b0c13.firebasestorage.app',
    iosBundleId: 'com.example.softinsaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkL134vEf_b3fIdY0xxRGCJrrTDAiJd9k',
    appId: '1:522600619451:web:409dad46ae65dffe30f89e',
    messagingSenderId: '522600619451',
    projectId: 'pint-b0c13',
    authDomain: 'pint-b0c13.firebaseapp.com',
    storageBucket: 'pint-b0c13.firebasestorage.app',
    measurementId: 'G-6EF12GWNSK',
  );
}
